### PR TITLE
December 2024 fixes

### LINKED ISSUE #1063: Unexpected Error
### Home Assistant Version

2024.11.1

### Installation Method

Using HACS

### Name of Council (if relevant)

Kirklees Council

### Issue Information

the component never finishes initialisation after last major update (bin colours)

`This error originated from a custom integration.

Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:250
integration: UK Bin Collection Data (documentation, issues)
First occurred: November 25, 2024 at 10:11:03 PM (6669 occurrences)
Last logged: 10:31:53 PM

[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x55cd10d25133 <unknown> #1 0x55cd10a59966 <unknown> #2 0x55cd10a960dc <unknown> #3 0x55cd10a96211 <unknown> #4 0x55cd10ad06c4 <unknown> #5 0x55cd10ab5bfd <unknown> #6 0x55cd10ace1c7 <unknown> #7 0x55cd10ab59a3 <unknown> #8 0x55cd10a8a46a <unknown> #9 0x55cd10a8b55e <unknown> #10 0x55cd10ce4cae <unknown> #11 0x55cd10ce88fe <unknown> #12 0x55cd10cf1f20 <unknown> #13 0x55cd10ce9923 <unknown> #14 0x55cd10cbcc0e <unknown> #15 0x55cd10d0cb08 <unknown> #16 0x55cd10d0cc97 <unknown> #17 0x55cd10d1d113 <unknown> #18 0x7fcbd7ed6b43 <unknown>
[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x55efbda8c133 <unknown> #1 0x55efbd7c0966 <unknown> #2 0x55efbd7fd0dc <unknown> #3 0x55efbd7fd211 <unknown> #4 0x55efbd8376c4 <unknown> #5 0x55efbd81cbfd <unknown> #6 0x55efbd8351c7 <unknown> #7 0x55efbd81c9a3 <unknown> #8 0x55efbd7f146a <unknown> #9 0x55efbd7f255e <unknown> #10 0x55efbda4bcae <unknown> #11 0x55efbda4f8fe <unknown> #12 0x55efbda58f20 <unknown> #13 0x55efbda50923 <unknown> #14 0x55efbda23c0e <unknown> #15 0x55efbda73b08 <unknown> #16 0x55efbda73c97 <unknown> #17 0x55efbda84113 <unknown> #18 0x7f3cbc509b43 <unknown>
[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x55799f98f133 <unknown> #1 0x55799f6c3966 <unknown> #2 0x55799f7000dc <unknown> #3 0x55799f700211 <unknown> #4 0x55799f73a6c4 <unknown> #5 0x55799f71fbfd <unknown> #6 0x55799f7381c7 <unknown> #7 0x55799f71f9a3 <unknown> #8 0x55799f6f446a <unknown> #9 0x55799f6f555e <unknown> #10 0x55799f94ecae <unknown> #11 0x55799f9528fe <unknown> #12 0x55799f95bf20 <unknown> #13 0x55799f953923 <unknown> #14 0x55799f926c0e <unknown> #15 0x55799f976b08 <unknown> #16 0x55799f976c97 <unknown> #17 0x55799f987113 <unknown> #18 0x7fbeaede7b43 <unknown>
[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x5568ecf25133 <unknown> #1 0x5568ecc59966 <unknown> #2 0x5568ecc960dc <unknown> #3 0x5568ecc96211 <unknown> #4 0x5568eccd06c4 <unknown> #5 0x5568eccb5bfd <unknown> #6 0x5568eccce1c7 <unknown> #7 0x5568eccb59a3 <unknown> #8 0x5568ecc8a46a <unknown> #9 0x5568ecc8b55e <unknown> #10 0x5568ecee4cae <unknown> #11 0x5568ecee88fe <unknown> #12 0x5568ecef1f20 <unknown> #13 0x5568ecee9923 <unknown> #14 0x5568ecebcc0e <unknown> #15 0x5568ecf0cb08 <unknown> #16 0x5568ecf0cc97 <unknown> #17 0x5568ecf1d113 <unknown> #18 0x7f3218b09b43 <unknown>
[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x558047231133 <unknown> #1 0x558046f65966 <unknown> #2 0x558046fa20dc <unknown> #3 0x558046fa2211 <unknown> #4 0x558046fdc6c4 <unknown> #5 0x558046fc1bfd <unknown> #6 0x558046fda1c7 <unknown> #7 0x558046fc19a3 <unknown> #8 0x558046f9646a <unknown> #9 0x558046f9755e <unknown> #10 0x5580471f0cae <unknown> #11 0x5580471f48fe <unknown> #12 0x5580471fdf20 <unknown> #13 0x5580471f5923 <unknown> #14 0x5580471c8c0e <unknown> #15 0x558047218b08 <unknown> #16 0x558047218c97 <unknown> #17 0x558047229113 <unknown> #18 0x7f6c16cc5b43 <unknown>
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 41, in parse_data
    return self._parse_data(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 74, in _parse_data
    wait_for_element(
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 18, in wait_for_element
    wait_for_element_conditions(driver, element_present, timeout=timeout)
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 23, in wait_for_element_conditions
    WebDriverWait(driver, timeout).until(conditions)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5582d34cb133 <unknown>
#1 0x5582d31ff966 <unknown>
#2 0x5582d323c0dc <unknown>
#3 0x5582d323c211 <unknown>
#4 0x5582d32766c4 <unknown>
#5 0x5582d325bbfd <unknown>
#6 0x5582d32741c7 <unknown>
#7 0x5582d325b9a3 <unknown>
#8 0x5582d323046a <unknown>
#9 0x5582d323155e <unknown>
#10 0x5582d348acae <unknown>
#11 0x5582d348e8fe <unknown>
#12 0x5582d3497f20 <unknown>
#13 0x5582d348f923 <unknown>
#14 0x5582d3462c0e <unknown>
#15 0x5582d34b2b08 <unknown>
#16 0x5582d34b2c97 <unknown>
#17 0x5582d34c3113 <unknown>
#18 0x7faa5bcefb43 <unknown>
`

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### LINKED ISSUE #1067: Norwich missing Garden Waste bin times
### Name of Council

Norwich City Council

### Issue Information

At https://maps.norwich.gov.uk/mynorwich/index.html, using NR4 7QE as a postcode and selecting any property you are given something like:

> Your waste and recycling are collected on alternate weeks.
> Your food waste is collected every week.
> 
> Your normal collection day: Thursday
> Your next collection: 28/11/2024
> We will be collecting: waste and food waste.
> [Your waste and recycling calendar](https://www.norwich.gov.uk/download/downloads/id/2623/Week_2_-_Thursday.pdf)
> 
> [What goes in my bin?](https://www.norwich.gov.uk/info/20264/what_goes_in_my_bin)
> 
> Garden waste
> Your garden waste is collected fortnightly.
> 
> Your normal collection day: Thursday
> Your next collection: 05/12/2024
> [Your garden waste calendar](https://www.norwich.gov.uk/download/downloads/id/3201/Garden_waste_calendar_week_2.pdf)

Whereas I get a date for Waste OR Recycling, and Food - I don't get a date for Garden Waste. Can this be added too?

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### LINKED ISSUE #1072: MertonCouncil: Unexpected error: No connection adapters were found for 'python collect_data.py MertonCouncil
### Name of Council

Merton Council

### Issue Information

Hi,

I followed the instructions and checked multiple times if everything is configured correctly but I can't seem to get this working. 
Below is the log. Any ideas what might be the issue? 

2024-12-06 16:54:04.989 DEBUG (MainThread) [custom_components.uk_bin_collection] Finished fetching 30 Merton data in 0.016 seconds (success: False)
2024-12-06 16:54:05.054 DEBUG (MainThread) [custom_components.uk_bin_collection.config_flow] Loaded council data for reconfiguration.
2024-12-06 16:54:13.065 DEBUG (MainThread) [custom_components.uk_bin_collection.config_flow] Reconfigure user input: {'name': 'Merton', 'council': 'Merton Council', 'update_interval': 12, 'url': 'python collect_data.py MertonCouncil https://myneighbourhood.merton.gov.uk/Wasteservices/WasteServices.aspx?Address=133+Wandle+Road+Morden+SM4+6AA&ID=25968221', 'timeout': 60, 'icon_color_mapping': '{        "Empty Standard General Waste":    {              "icon": "mdi:trash-can",              "color": "black"        } }'}
2024-12-06 16:54:13.066 DEBUG (MainThread) [custom_components.uk_bin_collection.config_flow] Mapped wiki name 'Merton Council' to council key 'MertonCouncil'.
2024-12-06 16:54:13.067 INFO (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Setting up UK Bin Collection.
2024-12-06 16:54:13.068 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Retrieved configuration: name=Merton, timeout=60, update_interval=12 hours, icon_color_mapping={        "Empty Standard General Waste":    {              "icon": "mdi:trash-can",              "color": "black"        } }
2024-12-06 16:54:13.068 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Built UKBinCollectionApp arguments: ['MertonCouncil', 'python collect_data.py MertonCouncil https://myneighbourhood.merton.gov.uk/Wasteservices/WasteServices.aspx?Address=133+Wandle+Road+Morden+SM4+6AA&ID=25968221']
2024-12-06 16:54:13.068 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  UKBinCollectionApp args: ['MertonCouncil', 'python collect_data.py MertonCouncil https://myneighbourhood.merton.gov.uk/Wasteservices/WasteServices.aspx?Address=133+Wandle+Road+Morden+SM4+6AA&ID=25968221']
2024-12-06 16:54:13.074 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  UKBinCollectionApp initialized and arguments set.
2024-12-06 16:54:13.075 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  DataUpdateCoordinator initialized with update_interval=12:00:00.
2024-12-06 16:54:13.075 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  HouseholdBinCoordinator initialized with update_interval=12 hours.
2024-12-06 16:54:13.075 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Starting data fetch with timeout=60 seconds.
2024-12-06 16:54:13.075 INFO (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Fetching latest bin collection data.
2024-12-06 16:54:13.080 ERROR (SyncWorker_19) [uk_bin_collection.uk_bin_collection.get_bin_data] Request Error: No connection adapters were found for 'python collect_data.py MertonCouncil https://myneighbourhood.merton.gov.uk/Wasteservices/WasteServices.aspx?Address=133+Wandle+Road+Morden+SM4+6AA&ID=25968221'
2024-12-06 16:54:13.082 ERROR (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Unexpected error: No connection adapters were found for 'python collect_data.py MertonCouncil https://myneighbourhood.merton.gov.uk/Wasteservices/WasteServices.aspx?Address=133+Wandle+Road+Morden+SM4+6AA&ID=25968221'
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ~~~~~~~~~~~~~~~~^
        council_module.CouncilClass(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        council_module_str=self.parsed_args.module,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 81, in get_and_parse_data
    page = self.get_data(address_url)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 124, in get_data
    full_page = requests.get(url, headers, verify=False, timeout=120)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'python collect_data.py MertonCouncil https://myneighbourhood.merton.gov.uk/Wasteservices/WasteServices.aspx?Address=133+Wandle+Road+Morden+SM4+6AA&ID=25968221'
2024-12-06 16:54:13.092 DEBUG (MainThread) [custom_components.uk_bin_collection] Finished fetching Merton data in 0.017 seconds (success: False)
2024-12-06 16:54:13.093 INFO (MainThread) [custom_components.uk_bin_collection.config_flow] Configuration updated for entry: 01JEEDH2KZ3YVS01MPYJS9RR2R


### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### LINKED ISSUE #1073: Missing ‘type’ or ‘collectiondate’ error in logs
### Name of Council

Rugby Borough Council

### Issue Information

Error returned is below.

`This error originated from a custom integration.

Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:282
integration: UK Bin Collection Data (documentation, issues)
First occurred: 01:19:27 (12 occurrences)
Last logged: 01:33:47

[UKBinCollection] Missing 'type' or 'collectionDate' in bin data: {'type': None, 'collectionDate': '12/12/2024'}
[UKBinCollection] Missing 'type' or 'collectionDate' in bin data: {'type': None, 'collectionDate': '19/12/2024'}
[UKBinCollection] Missing 'type' or 'collectionDate' in bin data: {'type': None, 'collectionDate': '28/12/2024'}
[UKBinCollection] Missing 'type' or 'collectionDate' in bin data: {'type': None, 'collectionDate': '02/01/2025'}
`

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### LINKED ISSUE #1076: Error reported after update to 0.122
### Name of Council

London Borough of Sutton

### Issue Information

Error reported after update to 0.122
Failed start up retrying
Home assistant version: 2024.12.1

`[UKBinCollection] Unexpected error: 'NoneType' object has no attribute 'find_next_sibling'
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ~~~~~~~~~~~~~~~~^
        council_module.CouncilClass(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        council_module_str=self.parsed_args.module,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/councils/LondonBoroughSutton.py", line 51, in parse_data
    .find_next_sibling("dd")
     ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_next_sibling'`

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### LINKED ISSUE #1078: Wandsworth Borough Council
### Name of Council

Wandsworth Borough Council

### Example Address/Postcode

SW12 8RD

### Additional Information

https://www.wandsworth.gov.uk/
https://www.wandsworth.gov.uk/my-property/
https://www.wandsworth.gov.uk/my-property/?UPRN=100022684035&propertyidentified=Select#result

### Verification

- [X] I''ve checked the [wiki](https://github.com/robbrad/UKBinCollectionData/wiki/Councils#contents) and verified that my council has not been added
- [X] I''ve checked that a request for my council does not already exist in the [Issues tracker](https://github.com/robbrad/UKBinCollectionData/issues?q=is%3Aopen+is%3Aissue+label%3A"council+request")
- [X] I have provided a tested working address/postcode/UPRN with bin collections available, as well as a link to the council''s website
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

### LINKED ISSUE #1080: Swale Updated URL
### Name of Council

Swale Borough Council

### Issue Information

Swale Borough Council have updated their URL to https://swale.gov.uk/bins-littering-and-the-environment/bins/check-your-bin-day

Please can this be updated.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### LINKED ISSUE #1084: Integration no longer works/sets up since recent update
### Home Assistant Version

2024.12.3

### Installation Method

Using HACS

### Name of Council (if relevant)

West Lindsey District Council

### Issue Information

The integration will not start and results in an error. I have tried deleting the address and setting it up from scratch. I'm running the latest prompted version.
`Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:250
integration: UK Bin Collection Data ([documentation](https://github.com/robbrad/UKBinCollectionData/wiki), [issues](https://github.com/robbrad/UKBinCollectionData/issues))
First occurred: 15 December 2024 at 10:48:01 (1353 occurrences)
Last logged: 17:31:03

[UKBinCollection] Unexpected error: can only concatenate str (not "relativedelta") to str
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ~~~~~~~~~~~~~~~~^
        council_module.CouncilClass(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        council_module_str=self.parsed_args.module,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/councils/WestLindseyDistrictCouncil.py", line 101, in parse_data
    full_date = bin_date + relativedelta(years=1)
                ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "relativedelta") to str`

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### LINKED ISSUE #1087: Food Waste Bin Date Incorrect & request to add bin colours (if possible)
### Name of Council

West Berkshire Council

### Issue Information

image

image

Looking at the  attached images, my black bin and recycling bin are showing the correct date, but my food waste bin is not. Looking at the raw data:

image

I can see that something is awry with the data retrieval.

Also, I am wondering if it would be possible to grab the colours of the background for each bin type and add them in to the data feed.

Thanks

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### LINKED ISSUE #1089: Bromley Borough Council dates are shifted by one year
### Name of Council

Bromley Borough Council 

### Issue Information

I have configured Bromley Borough Council and dates returned shows wrong year. Everything is shifted by a year. Council website shows only date and month not a years and parsers defaults to a wrong year.
I have tested the API call as follows:
curl -X 'GET' \
  'http://192.168.1.6:8080/api/bin_collection/BromleyBoroughCouncil?url=https%3A%2F%2Frecyclingservices.bromley.gov.uk%2Fwaste%2F6056991&web_driver=http%3A%2F%2F192.168.1.6%3A4444' \
  -H 'accept: application/json'

Returned object:
"{\n    \"bins\": [\n        {\n            \"type\": \"Food Waste\",\n            \"collectionDate\": \"23/12/2025\"\n        },\n        {\n            \"type\": \"Mixed Recycling (Cans, Plastics & Glass)\",\n            \"collectionDate\": \"23/12/2025\"\n        },\n        {\n            \"type\": \"Paper & Cardboard\",\n            \"collectionDate\": \"31/12/2025\"\n        },\n        {\n            \"type\": \"Non-Recyclable Refuse\",\n            \"collectionDate\": \"31/12/2025\"\n        }\n    ]\n}" 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### LINKED ISSUE #1101: Walsall Council No Longer Working
### Name of Council

Walsall Council

### Issue Information

Walsall Council no longer returns data. 
When adding Walsall Council, it only returns a single HA Entity for RAW JSON.
I have tried all variations of the URL i can think of but I get the same result of no returned data.

Other integrations such as Cannock Chase District Council work without issue.

The screenshots below shows my "Test" location using Walsall Council showing only a single entity and the contents of the single entity.

The location called "Home" is setup with Walsall Council but from a previous integration version with all entities showing a "This entity is no longer being provided by the uk_bin_collection integration". 

The final screenshot shows these previously working entities. 

image

image

image

Integration Version: 0.123.2
Previously working URL for testing: https://cag.walsall.gov.uk/BinCollections/GetBins?uprn=100071080513
UPRN: 100071080513
Postcode: WS8 7PW
URL to Bin Collections Page: https://cag.walsall.gov.uk/bincollections

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### PR DESCRIPTION
**Pull request by dp247**
## Bug fixes
- Closes #1063 
- Closes #1072 
- Closes #1073 
- Closes #1076 
- Closes #1080 
- Closes #1084 
- Closes #1087 
- Closes #1089
- Closes #1101 

- Add missing backticks to README.md

## Test fixes
- Fixes date format for Merton Council
- Fixes date logic for Swale Borough Council

## Additions
- Closes #1067 
- Closes #1078

### CODE REVIEW

**Comment by dp247** [comment]
Gonna fix some councils just like the good old days

@robbrad I appreciate you're very busy this time of year, but I noticed the Allure report has a 404 too (though I'm not raising it as an issue as its not directly plugin related lol).

**Comment by robbrad** [comment]
> Gonna fix some councils just like the good old days
> 
> 
> 
> @robbrad I appreciate you're very busy this time of year, but I noticed the Allure report has a 404 too (though I'm not raising it as an issue as its not directly plugin related lol).

Been trying to fix it today but no luck yet. I might separate out the publish to a different job so I can rerun it. At the moment it's an hour to find out if my changes worked 🥹

**Comment by dp247** [comment]
Hope you don't mind @m26dvd, I cherry-picked some of your fixes to go in here 😄

**Comment by robbrad** [comment]
@dp247  : https://github.com/robbrad/UKBinCollectionData/actions/runs/12383281990/job/34565689314?pr=1088#step:7:542

**Comment by dp247** [comment]
A job for tomorrow 👀

**Comment by m26dvd** [comment]
> Hope you don't mind @m26dvd, I cherry-picked some of your fixes to go in here 😄

No problem! I’ve not had time recently to do any more and it makes sense to batch release them rather than raise a PR for one fix!

**Comment by m26dvd** [comment]
@dp247 I’ve also got a new scraper for 1078 if you fancy including it here too!

**Comment by dp247** [comment]
> @dp247 I’ve also got a new scraper for 1078 if you fancy including it here too!

Sure thing, I'll pick it after work 😊

**Comment by robbrad** [comment]
@dp247 : are these two failures ok ? https://github.com/robbrad/UKBinCollectionData/actions/runs/12403956484/job/34628376787?pr=1088#step:7:567

If you are happy I will approve

**Comment by dp247** [comment]
> @dp247 : are these two failures ok ? https://github.com/robbrad/UKBinCollectionData/actions/runs/12403956484/job/34628376787?pr=1088#step:7:567
> 
> If you are happy I will approve

I'll take a look at them, though they don't seem to be breaking anything other than tests. Gonna stick another couple of issues in here too

**Comment by dp247** [comment]
Think I've cut the error log down as much as I can, so ready for review :D

**Comment by idarkside** [comment]
When will this be approved and megred in to the master branch?

**Comment by dp247** [comment]
> When will this be approved and megred in to the master branch?

We don't specify timelines since we're all volunteers, but it'll be merged after the code changes have been reviewed

**Comment by idarkside** [comment]
> > When will this be approved and megred in to the master branch?
> 
> We don't specify timelines since we're all volunteers, but it'll be merged after the code changes have been reviewed

No problem, apologies i am just waiting for the kirklees changes

**Comment by robbrad** [comment]
@dp247 hey buddy are you still working on these 4 failing or shall I merge? https://github.com/robbrad/UKBinCollectionData/actions/runs/12537086206/job/34960817194?pr=1088

**Comment by dp247** [comment]
> @dp247 hey buddy are you still working on these 4 failing or shall I merge? https://github.com/robbrad/UKBinCollectionData/actions/runs/12537086206/job/34960817194?pr=1088

Hello, merge this for now please - can always grab the failures later 😊

**Comment by robbrad** [comment]
@dp247 : can I ask a small favour can you make a small change to one of the council file to invoke the latest work flow?

I want to see the int tests report work for partial

The change doesnt have to be anything that would affect your work

**Comment by dp247** [comment]
> @dp247 : can I ask a small favour can you make a small change to one of the council file to invoke the latest work flow?
> 
> I want to see the int tests report work for partial
> 
> The change doesnt have to be anything that would affect your work

Haha, I can do... tomorrow when I get home 😅

**Comment by robbrad** [comment]
Don't bother. For some reason unknown it's still not working

**Review by robbrad — APPROVED** [review]
