### ISSUE TITLE
Error after update to 0.124.0. 

### ISSUE THREAD

**Issue by mimikm** [robbrad/UKBinCollectionData#1117]
### Home Assistant Version

2024.12.5

### Installation Method

Using HACS

### Name of Council (if relevant)

Tonbridge and Malling BC

### Issue Information

after update entities have been added but error occurs:  

`This error originated from a custom integration.

Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:250
integration: UK Bin Collection Data (documentation, issues)
First occurred: 21:20:24 (15 occurrences)
Last logged: 21:26:08

[UKBinCollection] Unexpected error: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ~~~~~~~~~~~~~~~~^
        council_module.CouncilClass(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        council_module_str=self.parsed_args.module,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/councils/TonbridgeAndMallingBC.py", line 73, in parse_data
    ).find("tbody")
      ^^^^
AttributeError: 'NoneType' object has no attribute 'find'`

Error on sintegration page shows:
' Unexpected error: 'NoneType' object has no attribute 'find'

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by m26dvd** [comment]
I've run some tests and it looks to parse okay to me.

Can you confirm if you are still having this issue and can you provide an example address that is having the issue please?

**Comment by mimikm** [comment]
Hi. After recent updates problem is gone and integration works like expected. 

Dom
